Revert "Implement EGL API for MESA_query_driver"
This reverts commit ff621a505594a3217f24fb785c51f43580f1bf78.

with default warnings configuration, this commit generates:

   ../src/egl/main/eglapi.c:2654:1: error: no previous prototype for
            ‘eglGetDisplayDriverConfig’ [-Werror=missing-prototypes]